name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  WIN10_SDK_PATH: "C:/Program Files (x86)/Windows Kits/10"
  WIN10_SDK_VERSION: 10.0.22621.0

jobs:
  cmake:
    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest, ubuntu-24.04-arm]
        build_type: [Release]
        toolchain: [clang, msvc, gcc]
        include:
          - os: macos-latest
            toolchain: clang
            c_compiler: clang
            cpp_compiler: clang++
            container: null
          - os: windows-latest
            toolchain: msvc
            c_compiler: cl
            cpp_compiler: cl
            container: null
          - os: ubuntu-latest
            toolchain: gcc
            c_compiler: gcc
            cpp_compiler: g++
            container:
              image: dockcross/manylinux_2_28-x64:latest
              options: --volume /:/host
          - os: ubuntu-24.04-arm
            toolchain: gcc
            c_compiler: gcc
            cpp_compiler: g++
            container: null
        exclude:
          - os: macos-latest
            toolchain: msvc
          - os: macos-latest
            toolchain: gcc
          - os: macos-15-intel
            toolchain: msvc
          - os: macos-15-intel
            toolchain: gcc
          - os: ubuntu-latest
            toolchain: msvc
          - os: ubuntu-latest
            toolchain: clang
          - os: ubuntu-24.04-arm
            toolchain: msvc
          - os: ubuntu-24.04-arm
            toolchain: clang
          - os: windows-latest
            toolchain: clang
          - os: windows-latest
            toolchain: gcc

    name: CMake-${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    env:
      SCCACHE_GHA_ENABLED: "true"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Windows SDK
      if: matrix.os == 'windows-latest'
      uses: GuillaumeFalourd/setup-windows10-sdk-action@v2.4
      with:
        sdk-version: 22621

    - name: Set up dependencies on linux
      if: matrix.os == 'ubuntu-latest'
      run: >
        dnf install -y mesa-libGL-devel libxcb libxcb-devel libX11-xcb libXcursor-devel libXrandr-devel libXinerama-devel libXi-devel libXext-devel libxkbcommon libxkbcommon-devel libxkbcommon-x11-devel mesa-vulkan-drivers wayland-protocols-devel wayland-devel

    - name: Set up dependencies on linux arm
      if: matrix.os == 'ubuntu-24.04-arm'
      run: >
        sudo apt-get install -y libgl1-mesa-dev libxcb1-dev libx11-xcb-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxkbcommon-dev libxkbcommon-x11-dev libvulkan-dev libwayland-dev wayland-protocols
        
    - name: Set up sccache
      if: matrix.os == 'ubuntu-latest'
      uses: mozilla-actions/sccache-action@v0.0.5

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: >
        cmake
        -S .
        -B out/${{ matrix.build_type }}
        -C .github/workflows/dawn-ci.cmake
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DENABLE_DESKTOP_GL=ON

    - name: Configure CMake (Mac)
      if: matrix.os == 'macos-latest' || matrix.os == 'macos-13'
      run: >
        cmake
        -S .
        -B out/${{ matrix.build_type }}
        -C .github/workflows/dawn-ci.cmake
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
        -DCMAKE_OSX_DEPLOYMENT_TARGET="10.15"

    - name: Configure CMake (Linux)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-24.04-arm'
      run: >
        cmake
        -S .
        -B out/${{ matrix.build_type }}
        -C .github/workflows/dawn-ci.cmake
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DENABLE_DESKTOP_GL=ON
        -DDAWN_USE_WAYLAND=ON

    - name: Build
      run: cmake --build out/${{ matrix.build_type }} --config ${{ matrix.build_type }}

    - name: Package
      run: |
        cmake --install out/${{ matrix.build_type }} --config ${{ matrix.build_type }} --prefix Dawn-${{ github.sha }}-${{ matrix.os }}-${{ matrix.build_type }}
        cmake -E tar cvzf Dawn-${{ github.sha }}-${{ matrix.os }}-${{ matrix.build_type }}.tar.gz Dawn-${{ github.sha }}-${{ matrix.os }}-${{ matrix.build_type }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Dawn-${{ github.sha }}-${{ matrix.os }}-${{ matrix.build_type }}
        path: Dawn-${{ github.sha }}-${{ matrix.os }}-${{ matrix.build_type }}.tar.gz
